spring:
  profiles:
    active: dev
  application:
      name: rest

---
spring:
  profiles: dev

  h2.console.enabled: true
  datasource.url: jdbc:h2:mem:testdb

springdoc.api-docs.path: /api-docs

server:
 port: 8080

---
spring:
  profiles: example

  h2.console.enabled: true
  datasource.url: jdbc:h2:mem:testdb

springdoc.api-docs.path: /api-docs

server:
  port: 8080

---
spring:
  profiles: test

---
spring:
  profiles: qa

---
spring:
  profiles: prod